fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
    hocon: "git://github.com/puppetlabs/puppetlabs-hocon.git"
  symlinks:
    puppetserver: "#{source_dir}"

